server:
  port: 8088
  servlet:
    session:
      timeout: PT2M


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/homework?
    username: Zhou
    password: homework123
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true